droplet/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^confirmation/(?P<code>.*)/$', views.confirmation_view, name='email_confirmation'),
    url(r'^ordermanage/$',views.OrderManage.as_view(),name='ordermanage'),
]

droplet/applications/urls.py
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns

from .views import redis_detail,product_list,postgresql_detail,ProductDetail
#from .api_views import api_product_detail,api_product_list,featured_products,FeaturedProductDetail

urlpatterns= (
    url(r'^redis_detail/$',redis_detail, name = 'redis_detail' ),
    url(r'^product_list/$',product_list,name = 'product_list'),
    url(r'^postgresql_detail/$',postgresql_detail,name='postgresql_detail'),
    url(r'^(\w+)/detail/$',ProductDetail.as_view(),name='product_detail'),
    #api
    # url(r'^api/product_list/$',api_product_list,name='api_product_list'),
    # url(r'api/product_detail/(?P<pk>[0-9]+)$',api_product_detail,name='api_product_detail'),
    # url(r'api/featured-products$',featured_products,name='featured_product'),
    # url(r'api/featured-products/(?P<pk>[0-9]+)$',FeaturedProductDetail.as_view(), name = 'featured_product_detail')
)

urlpatterns = format_suffix_patterns(urlpatterns)

droplet/clusterdbm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/console/urls.py
from django.conf.urls import include,url

from .views.staff import StaffConsole,staff_order
from .views.client import ClientConsole


urlpatterns = [
    url(r'^console/$',ClientConsole,name='console'),
    url(r'^orders/$',staff_order,name='orders'),
]

droplet/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

droplet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/templates/_brandname.html
DROPLET

droplet/templates/_navbar.html
<li {% if active_link == "Home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "Applications" %}class="active"{% endif %}><a href="{% url 'applications:product_list' %}">Applications</a></li>
<li {% if active_link == "Price" %}class="active"{% endif %}><a href="{% url 'price' %}">Price</a></li>
<li {% if active_link == "Network" %}class="active"{% endif %}><a href="{% url 'network' %}">Network</a></li>
<li {% if active_link == "About" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

droplet/templates/_navright.html
{% load thumbnail %}

{% if user.is_authenticated %}
  <li class="dropdown dropbar">
  <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown"aria-haspopup="true" aria-expanded="false">
<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
{{ user.get_full_name|truncatechars:20 }}
<span class="caret"></span>
</a>

    <ul class="dropdown-menu dropdown-list" role="menu">
      {% if user.is_superuser %}
        <li><a href = "/admin/applications/">Admin Console</a></li>
        <li><a href = "{% url 'panel:console' %}">Staff Console</a></li>
        <li><a href = "/crud/packages/packages/">Order Management</a></li>
        <li><a href = "{% url 'helpdesk_home' %}">Ticket Management</a></li>
        <li><a href="/crud/authtools/users/">Client Management</a></li>
        <li class="divider"></li>
    {% elif perms.authtools.can_display_client_panel %}
        <li><a href = "{% url 'panel:console' %}">My Console</a></li>
        <li><a href = "{% url 'helpdesk_home' %}">My Ticket</a></li>
        <li><a href = "/crud/packages/packages/">My Order</a></li>
        <li class="divider"></li>
    {% elif perms.authtools.can_display_staff_panel %}
        <li><a href = "{% url 'panel:console' %}">Staff Console</a></li>
        {# <li><a href = "{% url 'panel:orders' %}">Order Management</a></li>#}
        <li><a href = "/crud/packages/packages/">Order Management</a></li>
        <li><a href = "{% url 'helpdesk_home' %}">Ticket Management</a></li>
        <li><a href="/crud/authtools/users/">Client Management</a></li>
        <li class="divider"></li>
    {% endif %}
      {#<li><a href="{% url 'helpdesk_home' %}">Ticket</a></li>  the source code url name is helpdesk_home #}
      {#<li><a href="{% url 'profiles:show_self' %}">Profile</a></li>#}
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
    </ul>
  </li>
{% endif %}

droplet/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="About" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<li><a  href="{% url 'accounts:login' %}" >Log in</a></li>
<li><a  href="{% url 'accounts:signup' %}" >Sigh Up</a></li>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

<!-- style -->
{% block styles %}
	{{ block.super }}
	<link href="{% static 'site/css/About.css' %}" rel="stylesheet">
{% endblock styles %}

<!-- Benefits of the Django application -->
{% block container %}
<!--about-main-->
<hr />
<hr />
<main>
  <!--banner-->
  <figure class="about-top-figure">
    <picture>
      <source media = "(max-width:768px)" srcset = "imgs/windows-vps-small.png">
      <img src="{% static 'site/img/aboutBK.png' %}" />
      <ul class="SITEimg-titile">
        <li><a href="#datab-mlls">LLC</a></li>
        <li><a href="#offic-address">Office Address</a></li>
      </ul>
    </picture>
  </figure>
  <!--about-content-->
  <div class="about-container">
    <div class="damLLS-content">
      <h3 id="datab-mlls"> LLC</h3>
      <ul>
        <li>The site is a division of <a href="#"> LLC</a>.</li>
        <li>We are focused on <a href="#">Microsoft Windows hosting and SQL Server hosting</a>. This specific focus provides a professional and reliable database hosting and Web hosting service with superb technical support and customer service at <a href="#">reasonable prices</a>.</li>
        <li> LLC is attentive to its worldwide customers' needs seeking new and forward thinking solutions and development options.</li>
      </ul>
      <div class="img-wrap">
        <ul>
          <li><img src="{% static 'site/img/NetworkImg/Dallas_Datacenter.gif' %}" /></li>
          <li><img src="{% static 'site/img/NetworkImg/Dallas_Facility.gif' %}" /></li>
          <li><img src="{% static 'site/img/NetworkImg/Dallas_Cooling.gif' %}" /></li>
          <li><img src="{% static 'site/img/NetworkImg/Dallas_Support.gif' %}" /></li>
        </ul>
      </div>
      <p> LLC was founded in 2005 and is a privately held company based in Texas, USA.</p>
    </div>
    <div class="address-content">
      <h3 id="offic-address">Office Address</h3>
      <div class="address-wrap">
        <p>7017 Weis Drive Galveston, Texas 77551 USA</p>
        <img src="{% static 'site/img/address.png' %}"/>
      </div>
    </div>
  </div>
</main><!--main end-->
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(-96.800279, 32.78129);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

droplet/templates/network.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Redis{% endblock %}

{% block styles %}
  {{ block.super }}
  <link href="{% static 'site/css/ApplicationsPage.css' %}" rel="stylesheet">
  <link href="{% static 'site/css/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'site/css/Network.css' %}" rel="stylesheet">

{% endblock styles %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="Network" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<li><a  href="{% url 'accounts:login' %}" >Log in</a></li>
<li><a  href="{% url 'accounts:signup' %}" >Sigh Up</a></li>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>High End, Fully Redundant, Enterprise Class Data Center</h1>
      </div>
    </div>
  </div>
</div>

<div class="pageContent">
  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="compare">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Datacenter.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Data Center</h3>
                            <ul>
                                <li><a href="http://www.sqlservermart.com/">Shared Windows Hosting</a></li>
                                <li><a href="http://www.hyper-v-mart.com/">Windows Hyper-V Hosting</a></li>
                                <li><a href="http://www.dedicatedsqlserver.com/">Dedicated Windows Server</a></li>
                                <li><a href="#">Server Management Service</a></li>
                                <li><a href="#">Domain Name Registration</a></li>
                                <li><a href="#">SSL Certificates</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Facility.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Facility</h3>
                            <ul>
                                <li>SSAE 16 SOC-1 Type II compliant data centers</li>
                                <li>Full cabinet and half cabinet solutions</li>
                                <li>24/7/365 physical access</li>
                                <li>Pre-approved control access list with ID check in man-trap</li>
                                <li>Covered dock with three bays</li>
                                <li>Staging area and secure customer storage available</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Power.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Power</h3>
                            <ul>
                                <li>Redundant A, B, C and D power backup available via four 750 KVA UPS systems</li>
                                <li>Three 1.5 MW Cummins generators with load bank for testing</li>
                                <li>Lightning Protection System</li>
                                <li>14,400 volt main electrical service</li>
                                <li>Pre-action dry pipe fire detection and suppression</li>
                                <li>SSL Certificates</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Cooling.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Cooling</h3>
                            <ul>
                                <li>Four 500-ton Trane chillers</li>
                                <li>Liebert air handling units</li>
                                <li>Ice storage system with 46 ice storage tanks</li>
                                <li>Dual water mains with diverse entries</li>
                                <li>DAbundant chilled water capacity at 2(N) redundancy</li>
                                <li>SSL Certificates</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Network.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Network / Bandwidth</h3>
                            <ul>
                                <li>Access to a high-performance mesh of redundant, Tier-1 Internet backbone carriers through one managed connection</li>
                                <li>High-performance network-based solutions customized per your requirements</li>
                                <li>Cross-connects to all major carriers, including direct connections to Equinix</li>
                                <li>Multiple fiber entrance facilities</li>
                                <li>Multiple fiber optic service providers; dual/diverse feeds</li>
                                <li>Network consulting and management available from industry veterans</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4" >
                    <div class="thumbnail" style="height:500px">
                        <a href="#">
                            <img src="{% static 'site/img/NetworkImg/Dallas_Support.gif' %}"/>
                        </a>
                        <div class="caption">
                            <h3>Security and Support</h3>
                            <ul>
                                <li>Secure entrance with check-in station and man-trap</li>
                                <li>24 hour staffing of Network Operations Center</li>
                                <li>Free remote hands and eyes</li>
                                <li>Free bandwidth reporting</li>
                                <li>100% power SLA available</li>
                                <li>Perimeter fence with gate access control</li>
                                <li>Interior and exterior video surveillance</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

{% endblock container %}


<script src="{% static 'site/js/jquery-ui.js' %}"></script>

{% block scripts %}
{% endblock scripts %}

droplet/templates/new_base.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}

    <head>
        <meta charset="UTF-8">
        <title>cloud - droplet - vps</title>
        <meta name="keywords" content="vps droplet cloud ">
        <meta name="description" content="Windows VPS and Linux VPS Hosting Specialist">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <link rel="shortcut icon" href="{% static 'site/imgs/logo.ico' %}" />
            <link rel="stylesheet" href="{% static 'site/css/owl.carousel.css'%}" />
            <link rel="stylesheet" href="{% static 'site/css/owl.theme.css' %}" />
            <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" />
            <link rel="stylesheet" href="{% static 'site/css/jquery-ui.min.css' %}" />
            <link rel="stylesheet" href="{% static 'site/css/mainstyle.css' %}" />

        {% block styles %}
        {% endblock styles %}

    </head>

    <body>
        <header>
  		    <div class="others">
      			<a href="{{ settings.SITE_BASE_URL }}/portal/Main/frmNewTicket.aspx" target="_blank" title="Submit  Suport Ticket">
      				<img src="{% static 'site/imgs/others/open-ticket.png' %}" alt="open a ticket">
      			</a>
      			<a href="{{ settings.SITE_BASE_URL }}/clients/" target="_blank" title=" Billing System">
      				<img src="{% static 'site/imgs/others/billing-system.png'%}" alt="Billing System">
      			</a>
      			<a href="{{ settings.SITE_BASE_URL }}/portal/Main/Chat/frmClientChat.aspx?config=1" target="openChat" title="Chat with us!">
      				<img src="{% static 'site/imgs/others/online-chat.png' %}">
      			</a>
      		</div>

  		    <nav >
            <li>
              <a href="{{ settings.SITE_BASE_URL }}/" class="navbar-band logo">
                <img src="{% static 'site/imgs/logo.png' %}" alt="droplet Logo"  width="50%" height="30%">
              </a>
            </li>



      			<ul>
      				<li>
      					<a href="{{ settings.SITE_BASE_URL }}/" title="Home Page">
      						Home
      					</a>
      				</li>
      				<li class="applictions">
      					<a href="{% url 'applications:product_list' %}" title="vps-home">Applictions</a>
				</li>
      				<li>
      					<a href="{% url 'price' %}">
      						Price
      					</a>
      				</li>
      				<li>
      					<a href="{% url 'network' %}">
      						Network
      					</a>
      				</li>
      				<li>
      					<a href="{% url 'show_blogs' %}">
      						Blog
      					</a>
      				</li>
      				<li>
      					<a href="{% url 'about' %}">
      						Community
      					</a>
      				</li>
      				<li>
      					<a href="{% url 'about' %}">
      						About
      					</a>
      				</li>
      			</ul>

            <!-- <ul class="login-panel">
              <li class="logIn">
                <a  href="{% url 'accounts:login' %}">Log in</a>
              </li>
              <li class="signUp">
                <a  href="{% url 'accounts:signup' %}">Sign Up</a>
              </li>
            </ul> -->
            {% if not user.is_authenticated %}
            <ul class="login-panel">
              <li class="logIn">
                <a  href="{% url 'accounts:login' %}">Log in</a>
              </li>
              <li class="signUp">
                <a  href="{% url 'accounts:signup' %}">Sign Up</a>
              </li>
            </ul>
              {% else %}
                  {% include "_navright.html" %}
              {% endif %}
      		</nav>



  	    </header>

        {% block main-content %}
        {% endblock main-content %}

        {% block scripts %}
          <script src="{% static 'js/jquery.min.js'%}"></script>
          <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	        <script src="{% static 'owl/owl-carousel/owl.carousel.min.js' %}"></script>
	        <script src="{% static 'site/js/jquery-ui.js' %}"></script>
        {% endblock scripts %}
        <!--banner-js-demo-->
        <footer>
      		<section class="footer-main">
      			<section class="footer-list">
      				<ul>
      					<li>
      						<h3>Hosting Center</h3>
      					</li>
      					<li>
      						<a href="#">Windows VPS Servers</a>
      					</li>
      					<li>
      						<a href="#">Linux VPS Servers</a>
      					</li>
      					<li>
      						<a href="#">Dedicated Servers</a>
      					</li>
      					<li>
      						<a href="#">Windows VPS Management Servers</a>
      					</li>
      					<li>
      						<a href="#">Domain Registration</a>
      					</li>
      					<li>
      						<a href="#">SSL Certificates</a>
      					</li>
      				</ul>
      				<ul>
      					<li><h3>Support Center</h3></li>
      					<li>
      						<a href="#">Helpdesk</a>
      					</li>
      					<li>
      						<a href="#">Frequently Asked Questions</a>
      					</li>
      					<li>
      						<a href="#">Knowledgebase</a>
      					</li>
      					<li>
      						<a href="#">WebsitePanel Control Panel</a>
      					</li>
      				</ul>
      				<ul>
      					<li>
      						<h3>Imformation Center</h3>
      					</li>
      					<li>
      						<a href="#">About us</a>
      					</li>
      					<li>
      						<a href="#">Why Choose Our Service</a>
      					</li>
      					<li>
      						<a href="#">Network and Data Center</a>
      					</li>
      					<li>
      						<a href="#">Terms Of Service</a>
      					</li>
      				</ul>
      			</section>

      			<figure class="social">
      				<p>©  <span id="year">2017</span></p>
      				<ul>
      					<li>
      						<a href="#">
      							<img src="{% static 'site/imgs/facebook.png' %}">
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<img src="{% static 'site/imgs/google.png'%}">
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<img src="{% static 'site/imgs/twitter.png'%}">
      						</a>
      					</li>
      				</ul>
      			</figure>
      		</section>

      		<p>
      			Copyright © 2005 - 2016  LLC <br>
      			7017 Weis Dr., Galveston, TX 77551 409-877-4238
      		</p>
      	</footer>



        <script>
        		$(document).ready(function(){
        			$(function(){
        				$("#owl-demo").owlCarousel({
        						items:1,
        						autoPlay: true,
        						stopOmHover:true
        				});
        			});
        		});
        	</script>


    </body>


</html>