droplet/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^confirmation/(?P<code>.*)/$', views.confirmation_view, name='email_confirmation'),
    url(r'^ordermanage/$',views.OrderManage.as_view(),name='ordermanage'),
]

droplet/blog/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . views import * 
urlpatterns = [
    url(r'^create/$', Create, name = 'create_blog'),
    url(r'^modify/$', Modify, name = 'modify_blog'),
    url(r'^delete/$', Delete, name = 'delete_blog'),
    #Reverse for 'blog.articles' with arguments '(1,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
    #add (?P<blog_id>\d+)
    url(r'^article/(?P<blog_body_id>\d+)/$', Article, name = 'article'),
    url(r'^author/(?P<blog_author>\w+)/$', ArticleByAuthor, name = 'article_author'),
    url(r'^$', ShowBlogs, name = 'show_blogs'),
    url(r'^lists/', lists, name='list'),
    url(r'^news/', news, name='news'),
    url(r'^Python/', python, name='python'),
    url(r'^abouttest/', abouttest, name='abouttest'),
    url(r'^mytalk/', mytalk, name='mytalk'),
    url(r'^diary/', diary, name='diary'),
    url(r'^add_article/', add_article, name='add_article'),
    url(r'^sub_article/', sub_article, name='sub_article'),
    url(r'^del_article/(?P<blog_body_id>\d+)/$', del_article, name='del_article'),
]

droplet/clusterdbm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/blog/models.py
#coding=utf-8
from django.db import models
from django.utils import timezone
from datetime import datetime, date
# Create your models here.
'''
参考 http://www.dannysite.com/blog/7/
'''
from django.contrib import admin

# 标签
class Tag(models.Model):
	tag_name = models.CharField(verbose_name = '标签', max_length=20)
	create_time = models.DateTimeField( verbose_name = '创建时间', auto_now_add=True)

	def __unicode__(self):
		return u'%s' % (self.tag_name)
	def __str__(self):
		return u'%s' % (self.tag_name)
	class Meta:
		verbose_name = "标签"
		verbose_name_plural = "标签"

# 作者
class Author(models.Model):
	nickname = models.CharField( verbose_name = '昵称', max_length=20)
	work = models.CharField( verbose_name = '工作', max_length=20)
	company = models.CharField( verbose_name = '单位', max_length=50)
	email = models.CharField( verbose_name = '邮箱', max_length=20)

	def __unicode__(self):
		return u'%s' % (self.nickname)
	def __str__(self):
		return u'%s' % (self.nickname)
	
	class Meta:
		verbose_name = "作者"
		verbose_name_plural = "作者"
	
class AuthorAdmin(admin.ModelAdmin):
	list_display = ('nickname', 'email', 'company')
	search_fields = ('nickname',)
# 分类
class Classification(models.Model):
	name = models.CharField( verbose_name = '类别', max_length=20, default = '随笔')

	def __unicode__(self):
		return u'%s' % self.name
	def __str__(self):
		return u'%s' % self.name
	
	class Meta:
		verbose_name = "分类"
		verbose_name_plural = "分类"

# 文章
class Blogs(models.Model):
	TYPE_CHOICES  = {
	        ('Txt','文本'),
	        ('Blend','图文'),
	        ('Photo','图片'),
	        ('Link','链接'),
	}
	title = models.CharField( verbose_name = '标题', max_length = 150)
	subTitle = models.CharField(verbose_name = '子标题', max_length=50, blank=True)
	body = models.TextField(verbose_name = '内容')
	publish_time = models.DateTimeField(verbose_name = '发布时间', auto_now_add=True)
	update_time = models.DateTimeField(verbose_name = '更新时间', default = timezone.now())
	classification = models.ForeignKey(Classification, verbose_name = '分类', null = True)
	tags = models.ManyToManyField(Tag, verbose_name = '标签', blank=True)
	blog_type = models.CharField(verbose_name = '正文类型', max_length=50, default='Txt',choices = TYPE_CHOICES)
	blog_imgurl = models.CharField(verbose_name = '头像地址', max_length=50, blank=True, null=True)
	blog_author = models.ForeignKey(Author, verbose_name= '作者')
	blog_ismarkdown = models.BooleanField(verbose_name = '是否MD格式', default=False)
	blog_like = models.IntegerField( verbose_name = '喜欢数', null=True)
	blog_clicknum = models.IntegerField(verbose_name = '点击数', null=True)
	
	def __unicode__(self):
		return u'%s' % self.title
	def __str__(self):
		return u'%s' % self.title
	
	class Meta:
		verbose_name = "文章"
		verbose_name_plural = "博客"
		#db_table="data"  
		#app_label='UserDBs'
	

class BlogPostAdmin(admin.ModelAdmin):
	list_display = ('title', 'subTitle', 'classification', 'blog_author', 'publish_time', 'update_time') #替预览
	list_filter = ('publish_time',)
	exclude=[]#不包括
	#inlines=[Author]#类表出来，注意text类有f k
	#search_fields= ['title', 'classification', 'blog_author'] #搜索菜单
	search_fields= ('title', ) #搜索菜单
	date_hierarchy = 'publish_time'
	ordering = ('-publish_time',)
	#使用filter_horizontal，(支持拖拽),filter_vertical可以从现有的选项中多选。一个为横排，一个为竖排。
	filter_horizontal = ('tags',)
	fieldsets=[
		('必填',{'fields':['title','classification','blog_author', 'publish_time']}),  
		('选填',{'fields':['subTitle','algupdate_timeo']})  
	]	

admin.site.register(Blogs,BlogPostAdmin)
admin.site.register(Author, AuthorAdmin)
admin.site.register(Classification)
admin.site.register(Tag)

droplet/blog/views.py
#coding=utf-8

from django.shortcuts import render

# Create your views here.
from blog.models import Blogs, Author
from django.shortcuts import render_to_response
from django.template import RequestContext

def ShowBlogs(request):
	userinfo = Author.objects.first()
	blog_list = Blogs.objects.all().order_by('-publish_time')
	#print(blog_list)
	for blog in blog_list:
		print(', '.join(['%s:%s' % item for item in blog.__dict__.items()]))
	return render_to_response('blog_index.html')
	#return render_to_response('blogs.html', {'userinfo': userinfo, 'blogs':blog_list}, context_instance=RequestContext(request))

def Create(request):
	return

def Modify(request):
	return


def Delete(request):
	return

#----------------------------------------------------------------------
def Article(request, blog_id = ""):
	""""""
	#title=request.POST["blog_title"]
	#author=request.POST["blog_author"]
	userinfo = Author.objects.first()
	blog_list = Blogs.objects.get(id = blog_id)
	return render_to_response('article.html',{'userinfo': userinfo,'article':blog_list})

#----------------------------------------------------------------------
def ArticleByAuthor(request, blog_author = ""):
	""""""
	#title=request.POST["blog_title"]
	#author=request.POST["blog_author"]
	userinfo = Author.objects.first()
	blog_list = Blogs.objects.filter(blog_author__nickname__exact = blog_author)
	return render_to_response('article.html',{'userinfo': userinfo,'article':blog_list})



def lists(request):
	return render(request, 'python_list.html')


def news(request):
	return render(request, 'news.html')

def python(request):
	python_blog = BlogBody.objects.filter(blog_type='Python')[::-1]
	return render(request, 'python_list.html', {'python_blog': python_blog})


def abouttest(request):
	test_blog = BlogBody.objects.filter(blog_type='abouttest')[::-1]
	return render(request, 'test_list.html', {'test_blog': test_blog})


def mytalk(request):
	mytalk_blog = BlogBody.objects.filter(blog_type='mytalk')[::-1]
	return render(request, 'mytalk_list.html', {'mytalk_blog': mytalk_blog})


def diary(request):
	diary_blog = BlogBody.objects.filter(blog_type='diary')[::-1]
	return render(request, 'diary_list.html', {'diary_blog': diary_blog})


# 新增文章时调用add_article跳转新增页面,sub_article则吧新增文章处理后自动跳转到文章内容页详情
def add_article(request):
	return render(request, 'add_article.html')


def sub_article(request):
	cursor = connection.cursor()
	if request.method == 'POST':
		mytype = request.POST['article_type']
		title = request.POST['article_title']
		# body = markdown(request.POST['article_editor'])
		body = request.POST['article_editor']
		markdown = request.POST['article_markdown']
		print(markdown)
		updb = BlogBody(blog_title=title, blog_ismarkdown=markdown, blog_body=body, blog_type=mytype, blog_timestamp=time.strftime("%Y-%m-%d %X", time.localtime()), blog_author='点点寒彬', blog_clicknum=1, blog_like=0)
		updb.save()
		cursor.execute('select max(id) from grzx_blogbody where blog_type = %s ', [mytype])
		new_id = cursor.fetchone()
		return redirect('/grzx/article/' + str(new_id[0]) + '/')


# 处理文章删除和编辑
def del_article(request, blog_body_id):
	BlogBody.objects.get(id=blog_body_id).delete()
	return redirect('/')


def edit_article(request):
	pass

droplet/blog/templates/add_article.html
{% extends "base.html" %}
{% block bodycontent %}
<!--header end-->
<div id="mainbody" style="background-color: #333333">
  <div class="blogs">
    <div class="newlist">
  <h2>您当前的位置：<a href="{{ settings.SITE_BASE_URL }}/">首页</a>&nbsp;>&nbsp;新增文章</h2>

<ul>
{#    {% for x in diary_blog %}#}
{#        <p class="ptit"><b><a href="{% url 'article' x.id %}"> {{ x.blog_title }}</a></b></p>#}
{#        <p class="ptime">发布时间：{{ x.blog_timestamp }} 作者：{{ x.blog_author }}  分类：{{ x.blog_type }} </p>#}
{#        <div class="pcon">{{ x.blog_body }}</div>#}
{#        <div class="line"></div>#}
{#    {% endfor %}#}
<form method="post" action="/grzx/sub_article/">
    {% csrf_token %}
    <p>文章标题</p>
    <div>
        <select name="article_type" style="height: 20px; width: 120px;">
            <option value="Python" selected="selected">Python</option>
            <option value="abouttest">测试相关</option>
            <option value="mytalk">个人杂谈</option>
            <option value="diary">偶尔能想起来的日记</option>
        </select>
        <input name="article_title" type="text" style="height: 20px;width: 400px;" placeholder="请输入文章标题">
{#        <input name="article_markdown" type="checkbox" value="1">MarkDown#}
        <select name="article_markdown" style="height: 20px; width: 90px;">
            <option value="1" selected="selected">MarkDown</option>
            <option value="0">普通文本</option>
        </select>
    </div>
    <p>文章内容</p>
    <textarea name="article_editor" rows="55" style="width: 630px;"></textarea>
    <input type="submit" value="提交" style="margin-left: 300px;width: 60px;height: 20px;">
</form>
</ul>

<div class="page">
    <a title="Total record"><b>38</b></a>
    <b>1</b><a href="{{ settings.SITE_BASE_URL }}/jstt/index_2.html">2</a>
    <a href="{{ settings.SITE_BASE_URL }}/jstt/index_2.html">></a>
    <a href="{{ settings.SITE_BASE_URL }}/jstt/index_2.html">>></a></div>
</div>

    <!--bloglist end-->
    <aside>
        <div class="card" style="width: 280px;">
            <h1>About Me</h1>
            <p>网名：Sven Weng | 点点寒彬</p>
            <p>职业：测试工程师</p>
            <p>公司：华林证券</p>
            <p>Email：234827102@qq.com</p>
          <ul class="linkmore">
            <li><a href="{{ settings.SITE_BASE_URL }}/grzx/add_article" class="talk" title="给我留言"></a></li>
            <li><a href="{{ settings.SITE_BASE_URL }}/" class="address" title="联系地址"></a></li>
            <li><a href="{{ settings.SITE_BASE_URL }}/" class="email" title="给我写信"></a></li>
            <li><a href="{{ settings.SITE_BASE_URL }}/" class="photos" title="生活照片"></a></li>
    {#        <li><a href="{{ settings.SITE_BASE_URL }}/" class="heart" title="关注我"></a></li>#}
          </ul>
        </div>
      <div class="search">
        <form class="searchform" method="get" action="#">
          <input type="text" name="s" value="Search" onfocus="this.value=''" onblur="this.value='Search'">
        </form>
      </div>
{#      <div class="tuijian">#}
{#        <h2>栏目更新</h2>#}
{#        <ol>#}
{#          <li><span><strong>1</strong></span><a href="{{ settings.SITE_BASE_URL }}/">有一种思念，是淡淡的幸福,一个心情一行文字</a></li>#}
{#          <li><span><strong>2</strong></span><a href="{{ settings.SITE_BASE_URL }}/">励志人生-要做一个潇洒的女人</a></li>#}
{#          <li><span><strong>3</strong></span><a href="{{ settings.SITE_BASE_URL }}/">女孩都有浪漫的小情怀――浪漫的求婚词</a></li>#}
{#          <li><span><strong>4</strong></span><a href="{{ settings.SITE_BASE_URL }}/">Green绿色小清新的夏天-个人博客模板</a></li>#}
{#          <li><span><strong>5</strong></span><a href="{{ settings.SITE_BASE_URL }}/">女生清新个人博客网站模板</a></li>#}
{#          <li><span><strong>6</strong></span><a href="{{ settings.SITE_BASE_URL }}/">Wedding-婚礼主题、情人节网站模板</a></li>#}
{#          <li><span><strong>7</strong></span><a href="{{ settings.SITE_BASE_URL }}/">Column 三栏布局 个人网站模板</a></li>#}
{#          <li><span><strong>8</strong></span><a href="{{ settings.SITE_BASE_URL }}/">时间煮雨-个人网站模板</a></li>#}
{#          <li><span><strong>9</strong></span><a href="{{ settings.SITE_BASE_URL }}/">花气袭人是酒香―个人网站模板</a></li>#}
{#        </ol>#}
{#      </div>#}
{#      <div class="toppic">#}
{#        <h2>图文并茂</h2>#}
{#        <ul>#}
{#          <li><a href="{{ settings.SITE_BASE_URL }}/"><img src="../../static/images/k01.jpg">腐女不可怕，就怕腐女会画画！#}
{#            <p>伤不起</p>#}
{#            </a></li>#}
{#          <li><a href="{{ settings.SITE_BASE_URL }}/"><img src="../../static/images/k02.jpg">问前任，你还爱我吗？无限戳中泪点~#}
{#            <p>感兴趣</p>#}
{#            </a></li>#}
{#          <li><a href="{{ settings.SITE_BASE_URL }}/"><img src="../../static/images/k03.jpg">世上所谓幸福，就是一个笨蛋遇到一个傻瓜。#}
{#            <p>喜欢</p>#}
{#            </a></li>#}
{#        </ul>#}
{#      </div>#}
{#      <div class="clicks">#}
{#        <h2>热门点击</h2>#}
{#        <ol>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">慢生活</a></span><a href="{{ settings.SITE_BASE_URL }}/">有一种思念，是淡淡的幸福,一个心情一行文字</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">爱情美文</a></span><a href="{{ settings.SITE_BASE_URL }}/">励志人生-要做一个潇洒的女人</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">慢生活</a></span><a href="{{ settings.SITE_BASE_URL }}/">女孩都有浪漫的小情怀――浪漫的求婚词</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">博客模板</a></span><a href="{{ settings.SITE_BASE_URL }}/">Green绿色小清新的夏天-个人博客模板</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">女生个人博客</a></span><a href="{{ settings.SITE_BASE_URL }}/">女生清新个人博客网站模板</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">Wedding</a></span><a href="{{ settings.SITE_BASE_URL }}/">Wedding-婚礼主题、情人节网站模板</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">三栏布局</a></span><a href="{{ settings.SITE_BASE_URL }}/">Column 三栏布局 个人网站模板</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">个人网站模板</a></span><a href="{{ settings.SITE_BASE_URL }}/">时间煮雨-个人网站模板</a></li>#}
{#          <li><span><a href="{{ settings.SITE_BASE_URL }}/">古典风格</a></span><a href="{{ settings.SITE_BASE_URL }}/">花气袭人是酒香―个人网站模板</a></li>#}
{#        </ol>#}
{#      </div>#}
    </aside>
  </div>
  <!--blogs end-->
</div>
<!--mainbody end-->
{% endblock bodycontent %}

droplet/blog/templates/blogs.html
{% extends "blogbase_black_timeline.html" %}
{% load staticfiles %}

{% block navbar-left %}
{% include "_navbar.html" %}
{% endblock %}
{% block navbar-right %}

{% if not user.is_authenticated %}
<li><a  href="{% url 'accounts:login' %}" >Log in</a></li>
<li><a  href="{% url 'accounts:signup' %}" >Sigh Up</a></li>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block content %}
<div class="blogs">
<!--<div>{ { request }}</div>-->
	{% for blog in blogs %}
	<div id="index_view">
	<li><div>分类：{{ blog.classification }}</div></li>
	<li><div>发表时间：{{ blog.publish_time|date:"Y-m-d H:i" }}</div></li>
	<li><div class="blog_info2"><span class="blog_info2_list"><span class="li_small_2">标签：
	{% for tag in blog.tags.all %}
	{{ tag.tag_name }}
	{% endfor %}
	</span></span></div></li>
	<li>
		<div class="arrow_box">
			<div class="ti"></div>
			<input type='hidden' name='blog_title' value='{{ blog.title }}'/>
			<input type='hidden' name='blog_author' value='{{ blog.blog_author }}'/>
			<!--三角形-->
			<div class="ci"></div>
			<!--圆形-->
			<!--Reverse for 'blog.articles' with arguments '(1,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []-->
			<h2 class="title"><a href="{% url 'blog:article' blog.id %}" target="_blank" method='post'>{{ blog.title }}</a></h2>
			<ul class="textinfo">
			<a href="{% url 'blog:article_author' blog.blog_author %}"><img src="{{ blog.blog_imgurl }}"></a>
			<p> {{ blog.body }}</p>
			</ul>
			<ul class="details">
			<li class="likes"><a href="#">10</a></li>
			<li class="comments"><a href="#">34</a></li>
			<li class="icon-time"><a href="#">{{ blog.timestamp }}</a></li>
			</ul>
		</div>
	<!--arrow_box end--> 
	</li>
	</div><!--index_view end-->
	{% endfor%}
	<div class="card">
		<h1>About Me</h1>
		<p>网名：{{ reuset.user.nickname }}</p>
		<p>职业：{{ reuset.user.work }}</p>
		<p>公司：{{ reuset.user.company }}</p>
		<p>Email：{{ reuset.user.email }}</p>
		<h1></h1>
	<ul class="linkmore">
		<li><a href="{{ settings.SITE_BASE_URL }}/" class="talk" title="给我留言"></a></li>
		<li><a href="{{ settings.SITE_BASE_URL }}/" class="address" title="联系地址"></a></li>
		<li><a href="{{ settings.SITE_BASE_URL }}/" class="email" title="给我写信"></a></li>
		<li><a href="{{ settings.SITE_BASE_URL }}/" class="photos" title="生活照片"></a></li>
		<li><a href="{{ settings.SITE_BASE_URL }}/" class="heart" title="关注我"></a></li>
	</ul>
	</div>
</div><!--class blogs end-->
{% endblock %}