droplet/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
        views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^confirmation/(?P<code>.*)/$', views.confirmation_view, name='email_confirmation'),
    url(r'^ordermanage/$',views.OrderManage.as_view(),name='ordermanage'),
]

droplet/applications/urls.py
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns

from .views import redis_detail,product_list,postgresql_detail,ProductDetail
#from .api_views import api_product_detail,api_product_list,featured_products,FeaturedProductDetail

urlpatterns= (
    url(r'^redis_detail/$',redis_detail, name = 'redis_detail' ),
    url(r'^product_list/$',product_list,name = 'product_list'),
    url(r'^postgresql_detail/$',postgresql_detail,name='postgresql_detail'),
    url(r'^(\w+)/detail/$',ProductDetail.as_view(),name='product_detail'),
    #api
    # url(r'^api/product_list/$',api_product_list,name='api_product_list'),
    # url(r'api/product_detail/(?P<pk>[0-9]+)$',api_product_detail,name='api_product_detail'),
    # url(r'api/featured-products$',featured_products,name='featured_product'),
    # url(r'api/featured-products/(?P<pk>[0-9]+)$',FeaturedProductDetail.as_view(), name = 'featured_product_detail')
)

urlpatterns = format_suffix_patterns(urlpatterns)

droplet/clusterdbm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

import profiles.urls
import accounts.urls
import applications.urls
import comments.urls
from . import v1_api_urls
from .v2_api_urls import router

import packages.urls
import comments.urls
from .views import AboutPage,home,NetworkPage,Price
from comments.views import SaveComments
import console.urls
import blog.urls
import excel.urls

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^cdb/$', home, name='home'),
    #url(r'^cdb/$', views.HomePage.as_view(), name='home'),
    #url(r'^cdb/host/$', views.HostPage.as_view(), name='host'),
    #url(r'^cdb/solution/$', views.SolutionPage.as_view(), name='solution'),
    #url(r'^cdb/support/$', views.SupportPage.as_view(), name='support'),
    url(r'^cdb/about/$', AboutPage.as_view(), name='about'),
    url(r'^cdb/network/$', NetworkPage.as_view(), name='network'),
    url(r'^cdb/price/$',Price.as_view(),name='price'),
    url(r'^cdb/users/', include(profiles.urls, namespace='profiles')),
    url(r'^cdb/', include(accounts.urls, namespace='accounts')),
    url(r'^cdb/product/',include(applications.urls, namespace = 'applications')),
    url(r'^cdb/admin/', include(admin.site.urls)),
    url(r'^cdb/tinymce/', include('tinymce.urls')),
    url(r'^cdb/order/',include(packages.urls,namespace='order')),
    url(r'^cdb/comments/', include('comments.urls', namespace='comments')),
    url(r'^cdb/save_comments/$', SaveComments, name = 'save_comments'),
    url(r'^cdb/api-token-auth/', obtain_jwt_token),
    url(r'^cdb/helpdesk/', include('helpdesk.urls')),
    url(r'^cdb/panel/',include('console.urls',namespace='panel')),
    url(r'^cdb/crud/',include('crudbuilder.urls',namespace='crud')),
    url(r'^cdb/graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^cdb/draceditor', include('draceditor.urls',namespace='draceditor')),
    url(r'^cdb/blog/', include('blog.urls',namespace='blog')),
    url(r'^cdb/cdyd/', include('excel.urls',namespace='excel')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#api here
import accounts.api_urls
urlpatterns += [
    url(r'^cdb/user_api/',include(accounts.api_urls,namespace='user_api')),
    url(r'^cdb/v1/',include(v1_api_urls,namespace='v1')),
    url(r'^cdb/v2/',include(router.urls,namespace='v2')),
]

#rest_framework
urlpatterns += [
    url(r'^cdb/api_auth/', include('rest_framework.urls',namespace='rest_framework')),
]

droplet/templates/products/product_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load comments %}
{% load rank %}
{% load range %}

{% block title %}{{ block.super }}Postgresql{% endblock %}

<!-- style -->
{% block styles %}
	{{ block.super }}
	<link href="{% static 'site/css/detail_2017.css' %}" rel="stylesheet">
{% endblock styles %}


{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<li><a  href="{% url 'accounts:login' %}" >Log in</a></li>
<li><a  href="{% url 'accounts:signup' %}" >Sigh Up</a></li>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
    <hr/>
    <hr/>


	<div class="container detail-body">
				<div class="row">
					<div class="col-lg-9">
						<!--top-->
						<div class="detail-top">
							<div class="row">
								<div class="col-lg-6">
									<div class="des-box">
										<div class="des-top">
											<div class="des-logo">
												<img alt="SITE-redis" src="{% static 'site/img/redis.png' %}" />
											</div>
											<div class="des-title">
												<h2>Redis</h2>
												<h5>NoSQL Opensource</h5>
												<span class="starsBar">
													{% for _ in review.rating|range:0 %}
													<img title="gorgeous" alt="{{i}}" src="{% static 'site/img/products/review/star-on.png'%}">&nbsp;
													{% endfor %}
														<!--{-% endwith %-}-->
														
													{% for _ in review.rating|range:5 %}
													<img title="gorgeous" alt="{{i}}" src="{% static 'site/img/products/review/star-off.png' %}">&nbsp;
													{% endfor %}
												</span>
												<h5>12K pepole using</h5>
											</div>
										</div>
										<div class="des-txt">
											<p>Redis is the abbreviation of Remote Dictionary Server. The original developer of Redis is Salvatore Sanfilippo who was hired by VMware in March, 2010. Redis is a key-value data stored system which is based on memory. Redis is also an open source software and it usually is considered data structure server. Redis support lots of stored value types, including string, list, set, zset (sorted set) and hash. Besides, it provides Java，C/C++，C#，PHP，JavaScript，Perl，Object-C，Python，Ruby，Erlang and other programming languages. Moreover, compared to other NoSQL databases, it is easier to set up the performance level for Redis.</p>
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="fa10-box">
										<ul>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>
											<li>
												<i class="fa fa-cube"></i><span>Feature</span>
											</li>

										</ul>
									</div>
								</div>
							</div>
						</div>

						<!--more-detail-->
						<div class="more-detail">
							<p>Redis is the abbreviation of Remote Dictionary Server. The original developer of Redis is Salvatore Sanfilippo who was hired by VMware in March, 2010.  Redis is a key-value data stored system which is based on memory. Redis is also an open source software and it usually is considered data structure server. Redis support lots of stored value types, including string, list, set, zset (sorted set) and hash. Besides, it provides Java，C/C++，C#，PHP，JavaScript，Perl，Object-C，Python，Ruby，Erlang and other programming languages. Moreover, compared to other NoSQL databases, it is easier to set up the performance level for Redis.Redis is the abbreviation of Remote Dictionary Server. The original developer of Redis is Salvatore Sanfilippo who was hired by VMware in March, 2010.  Redis is a key-value data stored system which is based on memory. Redis is also an open source software and it usually is considered data structure server. Redis support lots of stored value types, including string, list, set, zset (sorted set) and hash. Besides, it provides Java，C/C++，C#，PHP，JavaScript，Perl，Object-C，Python，Ruby，Erlang and other programming languages. Moreover, compared to other NoSQL databases, it is easier to set up the performance level for Redis.</p>
						</div>

						<!--data-model-->
						<div class="detail-data">

								<div class="system-body">
									<ul>
										<li>
											<p><input type="checkbox" name="windows" value="windows" />Windwos Platform</p>
										</li>
										<li>
											<p><input type="checkbox" name="Linux" value="Linux" />Linux Platform</p>
										</li>
										<li>
											<p><input type="checkbox" name="BSD" value="BSD" />BSD Platform</p>
										</li>
										<li>
											<p><input type="checkbox" name="Mac OS" value="Mac OS" />Mac OS Platform</p>
										</li>
										<li>
											<a href="$">Other Platform</a>
										</li>
									</ul>
								</div>

								<div class="lang-body">
									<ul>
										<li>
											<p><input type="checkbox" name="JAVA" value="JAVA" />JAVA</p>
										</li>
										<li>
											<p><input type="checkbox" name="Python" value="Python" />Python</p>
										</li>
										<li>
											<p><input type="checkbox" name="C#" value="C#" />C#</p>
										</li>
										<li>
											<p><input type="checkbox" name="PHP" value="PHP" />PHP</p>
										</li>
										<li>
											<a href="$">Other PLanguages</a>
										</li>
									</ul>
								</div>

								<div class="database-body">
									<ul>
										<li>
											<p><input type="checkbox" name="MySQL" value="MySQL" />MySQL</p>
										</li>
										<li>
											<p><input type="checkbox" name="SQL" value="SQL" />SQL Server</p>
										</li>
										<li>
											<p><input type="checkbox" name="Oracle" value="Oracle" />Oracle</p>
										</li>
										<li>
											<p><input type="checkbox" name="MogoDB" value="MogoDB" />MogoDB</p>
										</li>
										<li>
											<a href="$">Other Database</a>
										</li>
									</ul>
								</div>

						</div>

						<!--reviews-->
						<div class="reviews-content">
							<div class="reviews-body">
								<h2>Revews(8)</h2>
								<div class="re-sone">
									<p>6/3/2017 By Name</p>
									<input type="text"/>
								</div>
								<div class="re-sone">
									<p>9/3/2017 By Name</p>
									<input type="text"/>
								</div>
								<div class="re-sone">
									<p>9/3/2017 By Name</p>
									<input type="text"/>
								</div>
								<div class="re-sone">
									<p>9/3/2017 By Name</p>
									<input type="text"/>
								</div>
								<div class="re-btnbox">
									<div class="rem-btn">
										Read More
									</div>
									<a class="addmre" href="@">Add My review</a>
								</div>
							</div>

							<div class="re-history">
								<div class="rehis-body">
									<h2>Released history</h2>
									<ul>
										<li>
											<a href="*">12/23/2015 Relased 2.1</a>
										</li>
										<li>
											<a href="*">12/23/2015 Relased 2.1</a>
										</li>
										<li>
											<a href="*">12/24/2015 Relased 2.2</a>
										</li>
										<li>
											<a href="*">12/26/2015 Relased 2.1</a>
										</li>
									</ul>
								</div>
							</div>
						</div>

					</div><!--col-lg-9-end-->

					<div class="col-lg-3">

							<a  class="gt6m-btn" href="#">Get Free 6 Montrhs Trial</a>

							<ul class="dis7-body">
								<li>
									<h3>Provider Information</h3>
									<div class="pi-box">
										<a href="#">VendorName</a>
										<p>Latest Version and date</p>
										<p>License Type</p>
									</div>
								</li>

								<li>
									<h3>Provider Information</h3>
									<div class="pi-box">
										<a href="#">VendorName</a>
										<p>Latest Version and date</p>
										<p>License Type</p>
									</div>
								</li>

								<li>
									<h3>Provider Information</h3>
									<div class="pi-box">
										<a href="#">VendorName</a>
										<p>Latest Version and date</p>
										<p>License Type</p>
									</div>
								</li>

								<li>
									<div class="pi2-box">
										<a href="#">VendorName</a>
										<a href="#">VendorName</a>
										<a href="#">VendorName</a>
										<a href="#">VendorName</a>
									</div>
								</li>

								<li>
									<div class="pi2-box">
										<h4>Document</h4>
									</div>
								</li>

								<li>
									<div class="pi2-box">
										<h4>Video</h4>

										<dd class="dd-content videoBar">
											<a href="#">
												<div class="play-video">
													<i class="fa fa-play play-video-fa"></i>
												</div>
												<img />
											</a>
										</dd>
									</div>
								</li>

								<li>
									<div class="pi2-box">
										<h4>ScreenShot</h4>
										<dd class="dd-content screenShot ">
												<img src="{% static 'site/img/star-on.png' %}" data-action="zoom" />
												<img src="{% static 'site/img/star-on.png' %}" data-action="zoom" />
												<img src="{% static 'site/img/star-on.png' %}" data-action="zoom" />
												<img src="{% static 'site/img/star-on.png' %}" data-action="zoom" />
										</dd>
									</div>
								</li>

							</ul>

							<a  class="gt6m-btn enda-btn" href="#">Get Free 6 Montrhs Trial</a>

					</div>
				</div>
			</div>
{% endblock %}




{% block footer %}
      <!-- Some social button for contact will do -->
    {{ block.super }}<!--base style-->
{% endblock %}

{% block scripts %}
<script src="{% static 'site/js/jquery.js' %}"></script>
<script src="{% static 'site/js/zooming.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock scripts %}

droplet/templates/products/product_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load rank %}

{% block title %}{{ block.super }}Applictions{% endblock %}

<!-- style -->
{% block styles %}
	{{ block.super }}
	<link href="{% static 'site/css/ApplicationsPage.css' %}" rel="stylesheet">
	<link href="{% static 'site/css/jquery-ui.min.css' %}" rel="stylesheet">

{% endblock styles %}


{% block navbar-left %}
  {% include "_navbar.html" with active_link="Applications" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<li><a  href="{% url 'accounts:login' %}" >Log in</a></li>
<li><a  href="{% url 'accounts:signup' %}" >Sigh Up</a></li>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<!-- title -->
<div class="container appContainer">
    {{ block.super }}
	<div class="row">
		<!--Applications Title-->
		<div class="col-md-12">
			<div class="page-title">
				<h1>Applictions</h1>
				<h3>SITE is an app library for server software. Install your favorite applications in your own servers or run them in the cloud. Select one app to get started or learn more about what makes SITE special.</h3>
                <span><p style="color:red" id="error"></p></span>
				<div class="input-group">
					<input id="tags" class="form-control">
					<span class="input-group-btn">
						<button id="product_search" class="btn btn-default" type="button">GO</button>
					</span>
				</div>
			</div>
		</div>
		<hr/>
		<!--Applications ShowBar-->
		<div class="col-md-12">
			<div class="row">
					<!--Left Selections-->
					<div class="col-md-2 col-sm-4 hidden-xs left_menu">
						<ul class="nav nav-pills nav-stacked">
							<li class="active">
								<a href="#">All</a>
							</li>
							<li><a href="#">SQL</a></li>
							<li><a href="#">NoSQL</a></li>
							<li><a href="#">CMS</a></li>
							<li><a href="#">Forum</a></li>
						</ul>
					</div>
					<!--Right Products-->
					<div class="col-lg-10">
						<div class="row">
                            {% if product_list %}
                                {% for product in product_list %}
                                    <div class="col-md-4 col-sm-6">
                                        <div class="product-frame">
                                            <div class="product-top">
                                                <div class="product-title">
                                                    <a href="{{ product.product_url }}">{{ product.name }}</a>
                                                    <span>{{ product.type }}</span>
                                                </div>
                                                <div class="product-icon">
                                                    <a href="{{ product.product_url }}"><span><img src="{{ settings.SITE_BASE_URL }}/static/site/img/stack-iconbar{{ product.name|lower }}-icon.png" alt="{{ product.name }}"/></span></a>
                                                </div>
                                            </div>
                                            <div class="product-mid">
                                                <p>{{ product.summary|safe }}</p>
                                            </div>
                                            <div class="product-statsWrapper">
                                                <div class="row">
                                                    <div class="col-sm-4 col-xs-5">
                                                        <div class="product-graphic">{{ product.name|ranking }}</div>
                                                        <div class="product-stat-title">Rank</div>
                                                    </div>
                                                    <div class="col-sm-4 col-xs-5">
                                                        <div class="product-graphic">
                                                            {{ product.name|client }}
                                                        </div>
                                                        <div class="product-stat-title">Client</div>
                                                    </div>
                                                    <div class="col-sm-4 col-xs-5">
                                                        <div class="product-graphic">
                                                            {{ product.first_release_date|l_year }}
                                                            <span>yrs</span>
                                                        </div>
                                                        <div class="product-stat-title">Age</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="product-bottom">
                                                <div class="row">
							<div class="bottomBar product-btn">
								<div class="col-xs-12">
									<a href="{{ settings.SITE_BASE_URL }}/product{{ product.name }}/detail/"><span style="float: left;">More Details</span></a>
									<a href="{% url 'order:makeorder' %}?p={{ product.name }}"><span style="float: right;">Order Now</span></a>
								</div>
							</div>
						</div>
					</div>
                                        </div>
                                    </div><!--product1-->
                                {% endfor %}
                            {% else %}
                                <h1 class="text-danger text-center">The product you query,does not exist yet! </h1>
                            {% endif %}
			</div>
			</div>
			</div>
		</div>
	</div>
</div>



{% endblock container %}

{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'site/js/jquery-ui.js' %}"></script>
<script>
	$(function() {
		var availableTags = [
			"MySQL","Gitlab","Hadoop","Django","Cassandra","Redis","PostgreSQL","mongoDB"
		];
		$( "#tags" ).autocomplete({
			source: availableTags
		});
	});
	$("#tags")
			.focus(function(){$(this).val('')})
			.blur(function(){
				var $this = $(this);

			($this.val() === '')? $this.val('search...') : null;
	});

    $("#product_search").click(function() {
        if ($("#tags").val() == "" || $("#tags").val() == "search..." ) {
            $('#error').text("enter some thing to forward");
            return false;
        }
        var query_product=$("#tags").val();
        $.ajax(
        {
            type:"post",
            url:"{% url 'applications:product_list' %}",
            data:{"query_product":query_product,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',},
            datatype:"text",
            async:false,
            success:function(result)
            {

{#                  $('#application-list').html(result.result)#}
                if(result.result=="-1")
                {
                    $('#error').text("Sorry the app does not exists,you search another app, or you can waitting a while It's will coming soon!");
                    $("#tags").val("");
                    $("#tags").focus();
                   //return false
                }
                else
                {
                    $('#error').text("");
                    $("#tags").val("");
                    $("#tags").focus();
                    var product_title = result.result;
                    $("a[title != "+ product_title + "]").hide();
                };
            },
        });
    })
</script>
{% endblock scripts %}

droplet/templates/products/redis_detail.html
{% extends "base.html" %}

{% load staticfiles %}
<!--{% load crispy_forms_tags %}-->
<!-- {-% load threadedcomments_tags %} -->
{% load comments %}

{% block title %}{{ block.super }}Redis{% endblock %}

<!-- style -->
{% block styles %}
	{{ block.super }}
	<link href="{% static 'site/css/DetailPage.css' %}" rel="stylesheet">
{% endblock styles %}


{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
    <hr/>
    <hr/>
    <div class="container">
    		<div class="navbar navbar-default Redis-navbar" role="navigation">
    			<div class="navbar-inner container-fluid">
    				<ul class="nav navbar-nav">
    					<li class="active"><a href="#">Overview</a></li>
    					<li><a href="#">Overview</a></li>
    					<li class="dropdown">
    						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Over<span class="caret"></span></a>
    						<ul class="dropdown-menu" role="menu">
						{% for name in productsNames %}
    							<li><a href="{% url 'applications:product_detail' name %}">{{ name }} </a></li>
						{% endfor %}
    						</ul>
    					</li>
    					<li><a href="#">Overview</a></li>
    					<li><a href="#">Overview</a></li>
    				</ul>
    			</div>
    		</div>
    </div>
	{% for k, v in reviews.items %}
	{% if k == "Redis" %}
	{% for review in v %}
	{% if forloop.first %}
		<div class="container" id="newcomment">
			<div class="row">
				<div class="col-lg-6">
					<div class="Page-text">
						{% render_comment_form for review %}
					</div>
				</div>
			</div>
		</div>
	{% endif %}
	<div id="DetailPage1{{ forloop.counter }}">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="products-show">
						<img src="{% static 'site/img/products/Cloud.png' %}" alt=""/>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="Page-text">
						<p>
						<a class="btn btn-primary btn-xs pull-right" href="#new_comment">Write a Review &rarr;</a>
						</p>
						<p>
						<h5>by {{ review.created_by }} on {{ review.created_date }}
						<span title="gorgeous" class="rating-stars" data-score={{ review.rating }}>
							<!--{-% with ''|center:review.rating as range %-}-->
							<!--{-% for _ in range %-}-->
						{% load range %}
						{% for _ in review.rating|range %}
						<img title="gorgeous" alt="{{i}}" src="{% static 'site/img/products/review/star-on.png'%}">&nbsp;
						{% endfor %}
							<!--{-% endwith %-}-->
							
						{% for _ in review.rating|range:5 %}
						<img title="gorgeous" alt="{{i}}" src="{% static 'site/img/products/review/star-off.png' %}">&nbsp;
						{% endfor %}
						</p>
						<p>
						<input name="comment[rating]" type="hidden" readonly="" value={{review.rating}}>
						</span>
						</h5>
						</p>
						<h5>{{	review.reviews	}}</h5>
						<p>
						Was this review helpful to you?
						<a class="btn btn-default btn-xs vote-up" href="#">Yes</a>
						<a class="btn btn-default btn-xs vote-down" href="#">No</a>
						</p>
						<div class="products-button">
							<span><a href="#">Cloud Applications</a></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endfor %}
{% endif %}
{% endfor %}

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/jquery.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock scripts %}